// Random Motivational Quotes in Urdu
const quotes = [
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream big and dare to fail. – Norman Vaughan",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Wish it. Do it.",
    "Success is the sum of small efforts, repeated day-in and day-out. – Robert Collier",
    "Your passion is waiting for your courage to catch up. – Isabelle Lafleche",
    "Magic is believing in yourself, if you can do that, you can make anything happen. – Johann Wolfgang von Goethe",
    "If you can dream it, you can achieve it. – Zig Ziglar",
    "Don’t stop until you’re proud.",
    "Great things never come from comfort zones.",
    "Success is what happens after you have survived all your mistakes. – Anora Lee",
    "The future depends on what you do today. – Mahatma Gandhi",
    "Don’t wish it were easier. Wish you were better. – Jim Rohn",
    "Believe in yourself and all that you are. – Christian D. Larson",
    "Your only limit is your mind.",
    "Push harder than yesterday if you want a different tomorrow.",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "You are capable of more than you know.",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "The secret of getting ahead is getting started. – Mark Twain",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "Keep your eyes on the stars, and your feet on the ground. – Theodore Roosevelt",
    "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
    "Don’t wait for opportunity. Create it.",
    "Hard work beats talent when talent doesn’t work hard. – Tim Notke",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "The harder you work, the luckier you get. – Gary Player",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
    "Opportunities don't happen. You create them. – Chris Grosser",
    "Don't wait for the perfect moment. Take the moment and make it perfect.",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
    "Success isn't just about what you accomplish in your life; it's about what you inspire others to do.",
    "Don't let what you cannot do interfere with what you can do. – John Wooden",
    "The best way to predict the future is to create it. – Peter Drucker",
    "You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
    "Your time is limited, don't waste it living someone else's life. – Steve Jobs",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "The secret to success is to know something nobody else knows. – Aristotle Onassis",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "Success is a journey, not a destination. – Arthur Ashe",
    "The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "I never dreamed about success. I worked for it. – Estee Lauder",
    "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
    "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "The future depends on what you do today. – Mahatma Gandhi",
    "Don't let what you cannot do interfere with what you can do. – John Wooden",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
    "Your time is limited, don't waste it living someone else's life. – Steve Jobs",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "Success is a journey, not a destination. – Arthur Ashe",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "I never dreamed about success. I worked for it. – Estee Lauder",
    "The secret of success is consistency of purpose. – Benjamin Disraeli",
    "Success is getting what you want, happiness is wanting what you get. – W. P. Kinsella",
    "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do. – Pelé",
    "Success is the sum of small efforts, repeated day-in and day-out. – Robert Collier",
    "The key to success is to focus on goals, not obstacles.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Stay focused and never give up.",
    "Practice makes perfect.",
    "Believe in your abilities.",
    "Every expert was once a beginner.",
    "Consistency is key.",
    "Keep pushing forward.",
    "Learn from your mistakes.",
    "Stay curious and explore.",
    "Small steps lead to big results.",
    "Your effort determines your success.",
    "Embrace the challenge.",
    "Stay positive and motivated.",
    "Keep your goals in sight.",
    "Hard work pays off.",
    "Never stop learning.",
    "Stay dedicated to your studies.",
    "Success is a journey, not a destination.",
    "Stay organized and plan ahead.",
    "Push your limits.",
    "Stay disciplined.",
    "Focus on progress, not perfection.",
    "Keep a growth mindset.",
    "Take one step at a time.",
    "Stay resilient.",
    "Believe you can achieve.",
    "Keep your eyes on the prize.",
    "Stay determined.",
    "Embrace the process.",
    "Stay patient and persistent.",
    "Keep challenging yourself.",
    "Stay inspired.",
    "Your hard work will pay off.",
    "Stay committed to your goals.",
    "Keep striving for excellence.",
    "Stay enthusiastic about learning.",
    "Never lose sight of your dreams.",
    "Stay motivated every day.",
    "Push through the tough times.",
    "Stay eager to learn more.",
    "Keep building your skills.",
    "Stay focused on your studies.",
    "Believe in your potential.",
    "Stay strong and keep going.",
    "Keep your spirits high.",
    "Stay motivated, stay successful.",
    "Push yourself to excel.",
    "Stay sharp and attentive.",
    "Keep your knowledge growing.",
    "Stay proactive in your learning.",
    "Believe in continuous improvement.",
    "Stay engaged and participate.",
    "Keep a positive attitude.",
    "Stay organized and efficient.",
    "Push for your best.",
    "Stay motivated by your goals.",
    "Keep your focus intact.",
    "Stay inspired by success stories.",
    "Believe in the power of practice.",
    "Stay committed to mastering CSS.",
    "Keep advancing your skills.",
    "Stay motivated through challenges.",
    "Push your boundaries.",
    "Stay dedicated and passionate.",
    "Keep your enthusiasm alive.",
    "Stay focused on your progress.",
    "Believe in your study habits.",
    "Stay determined to succeed.",
    "Keep learning new techniques.",
    "Stay motivated by your achievements.",
    "Push through distractions.",
    "Stay consistent in your practice.",
    "Keep building your expertise.",
    "Stay positive during tough times.",
    "Believe in your study routine.",
    "Stay driven towards success.",
    "Keep enhancing your knowledge.",
    "Stay motivated by your vision.",
    "Push yourself beyond limits.",
    "Stay disciplined in your studies.",
    "Keep your learning goals clear.",
    "Stay inspired to achieve more.",
    "Believe in your dedication.",
    "Stay focused on mastering CSS.",
    "Keep progressing every day.",
    "Stay resilient in your studies.",
    "Push towards your academic goals.",
    "Stay enthusiastic about CSS.",
    "Keep striving for mastery.",
    "Stay committed to excellence.",
    "Believe in your academic journey.",
    "Stay motivated to excel in CSS.",
    "Keep your passion for learning alive.",
    "Stay focused on your educational path.",
    "Push yourself to understand deeply.",
    "Stay dedicated to your CSS goals.",
    "Keep your motivation strong.",
    "Stay positive and keep learning.",
    "Believe in your ability to succeed.",
    "Stay driven to achieve your best.",
    "Keep your study sessions productive.",
    "Stay motivated by your future success."
];


function displayRandomQuote() {
    const quoteElement = document.getElementById('quote');
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.innerHTML = quotes[randomIndex];
}

// Execute on page load
window.onload = displayRandomQuote;

// Light/Dark Mode Toggle
const toggle = document.getElementById('toggle');
const currentTheme = localStorage.getItem('theme') ? localStorage.getItem('theme') : null;

if (currentTheme) {
    document.documentElement.setAttribute('data-theme', currentTheme);

    if (currentTheme === 'dark') {
        toggle.checked = true;
    }
}

toggle.addEventListener('change', function(e) {
    if (e.target.checked) {
        document.documentElement.setAttribute('data-theme', 'dark');
        localStorage.setItem('theme', 'dark');
    } else {
        document.documentElement.setAttribute('data-theme', 'light');
        localStorage.setItem('theme', 'light');
    }
});
